name: dash_call
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sip_ua: ^1.0.1
  provider: ^6.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_callkit_incoming: ^2.0.0+1  
  uuid: ^4.5.1  
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/